### ISSUE TITLE
Complire error – Property 'avatarURL' does not exist on type 'Member | MentionedUser'.

### ISSUE THREAD

**Issue by EternallLight** [Skillz4Killz/Discordeno-bot-template#11]
```
TS2339 [ERROR]: Property 'avatarURL' does not exist on type 'Member | MentionedUser'.
  Property 'avatarURL' does not exist on type 'MentionedUser'.
          icon_url: member.avatarURL(),
```

If I change avatar.ts to

```
const member = message.member();
```

it complies ok, but that's not what is intended.

Actually, I don't quite get this part:

```
    const member = message.mentions.length
      ? message.mentions()[0]
      : message.member();
```

In the source code we have `mentions: MentionedUser[];` in MessageCreateOptions interface and ` mentions: () => data.mentions.map((mention) => message.guild()?.members.get(mention.id)!),` in createMessage. But it can't be both function and array. How is it meant to work?

**Comment by Skillz4Killz** [comment]
@EternallLight Can you tell me what version you are on? This was fixed in the v4.0.1 release if I am not mistaken. If you are using v4 branch this should be fixed with a `deno cache --reload mod.ts`. Might just need a simple update to have this fixed.

The method in the createMessage will override the mentions property in MessageCreateOptions.

First this ...data spreads all properties in a new object called message
![image](https://user-images.githubusercontent.com/23035000/82929374-8cb41180-9f51-11ea-965e-212305cba8d2.png)

Anything defined after it with the same name is basically overriding. It's a shorthand way of `Object.assing(obj1, obj2)`

**Comment by EternallLight** [comment]
@Skillz4Killz yeah, `cache --reload` helped. Guess I was looking on the latest pulled source code, but had v4.0 in deno cache. Hope a Deno plugin is going to land on Webstorm to remind me to update the cache. Thanks!

**Comment by Skillz4Killz** [comment]
If you have Velociraptor installed you can just do `vr dev` or make it any name you like in the scripts file https://github.com/Skillz4Killz/Discordeno-bot-template/blob/83e0e4236a06999d3ec40369cd2b6cf4cdcb46b0/scripts.yml#L8
